### ISSUE TITLE
运行你项目的时候，安装依赖报错了，请求解决方案

### ISSUE THREAD

**Issue by lvanboy** [ShanaMaid/vue-163-music#1]
These dependencies were not found:

* strip-ansi in ./~/.2.18.0@webpack-hot-middleware/client.js?noInfo=true&reload=
true
* ansi-html in ./~/.2.18.0@webpack-hot-middleware/client-overlay.js
* html-entities in ./~/.2.18.0@webpack-hot-middleware/client-overlay.js
* babel-runtime/helpers/typeof in ./src/filters/index.js
* babel-runtime/core-js/number/parse-int in ./src/filters/index.js, ./~/.6.4.1@b
abel-loader/lib!./~/.11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src
/components/footers.vue
* babel-runtime/core-js/get-iterator in ./src/store/search.js, ./~/.6.4.1@babel-
loader/lib!./~/.11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/comp
onents/playlist/home.vue and 2 others
* babel-runtime/core-js/set in ./src/store/search.js, ./~/.6.4.1@babel-loader/li
b!./~/.11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/components/se
arch.vue
* babel-runtime/helpers/slicedToArray in ./src/deal/playlist.js
* babel-runtime/helpers/toConsumableArray in ./~/.6.4.1@babel-loader/lib!./~/.11
.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/components/search.vue
* babel-runtime/core-js/object/keys in ./~/.6.4.1@babel-loader/lib!./~/.11.3.4@v
ue-loader/lib/selector.js?type=script&index=0!./src/components/search.vue

To install them, you can run: npm install --save strip-ansi ansi-html html-entit
ies babel-runtime/helpers/typeof babel-runtime/core-js/number/parse-int babel-ru
ntime/core-js/get-iterator babel-runtime/core-js/set babel-runtime/helpers/slice
dToArray babel-runtime/helpers/toConsumableArray babel-runtime/core-js/object/ke
ys

**Comment by ShanaMaid** [comment]
报错里面不是提供了解决方案和问题的所在了吗？These dependencies were not found:，依赖没找到。部分依赖可能被墙了，要么翻墙安装，要么试试用淘宝镜像安cnpm装试试。或使用下以下命令
npm install --save strip-ansi ansi-html html-entit
ies babel-runtime/helpers/typeof babel-runtime/core-js/number/parse-int babel-ru
ntime/core-js/get-iterator babel-runtime/core-js/set babel-runtime/helpers/slice
dToArray babel-runtime/helpers/toConsumableArray babel-runtime/core-js/object/ke
ys
