### ISSUE TITLE
您好，请教如何实现@focus和@blur

### ISSUE THREAD

**Issue by Huitimkit** [ShanaMaid/vue-163-music#5]
请问您是如何实现@focus和@blur事件的，
我查看官方文档并没有两个事件的介绍，
同时我也阅读了您的源码，没有找到有自定义指令
自己尝试并没有效果😢，烦请指教指教
```
<span @focus="display" @blur="display" tabindex="1">向日葵与薄荷草</span>
<em @focus="display" @blur="display" tabindex="1"></em>
```

**Comment by ShanaMaid** [comment]
可以直接使用，官方封装好了，只是举例的时候只用了@click，原生事件去掉on加上事件名就行了
比如onClick、onFocus     ，@click、@focus

**Comment by Huitimkit** [comment]
@ShanaMaid 我又试了一次，还是不起作用，是跟tabindex有关系？

**Comment by Huitimkit** [comment]
刚刚试了一下，学您加上tabindex就起作用了，这其中是有什么原理吗？

**Comment by ShanaMaid** [comment]
对于普通的div/span等元素节点是不能直接获取焦点的，需要用到tabindex

**Comment by Huitimkit** [comment]
好的，感谢感谢
